# Generated by Django 2.1.2 on 2018-11-22 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.TextField()),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.TextField()),
                ('name', models.CharField(default='', max_length=400)),
                ('phone', models.TextField(default='')),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
    ]
