version: "3"
services:

  postgresql-server:
    # image: postgres:alpine
    image: postgres:10.5-alpine
    container_name: 'microservice-pgsql-test-server'
    restart: always
    ports:
      - 5432:5432 
    volumes:
      - ./data/postgres/db:/var/lib/postgresql/data
      - ./data/postgres/logs:/var/log/postgresql
    environment:
      POSTGRES_USER: postgres 
      POSTGRES_PASSWORD: postgres123
      POSTGRES_DB: microSERVICE
      PGDATA: /var/lib/postgresql/data/pgdata       
    networks:
      - microservice-testnet 

  mongodb-server:
    image: mongo:3.4.16-jessie 
    container_name: 'microservice-mongodb-test-server'
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pwd123  
    volumes: 
      - ./data/mongo/db:/data/db  
      - ./data/mongo/logs:/var/log/mongodb          
    networks:
      - microservice-testnet 

networks:
  microservice-testnet: